In [1]:
import numpy as np 

In [4]:
a = np.array([[10,15]])
b = np.array([[1,2]])

print(a)
print(b)


print(a + b)
print(a.T + b.T)
print((a + b).T)

[[10 15]]
[[1 2]]
[[11 17]]
[[11]
 [17]]
[[11]
 [17]]


In [5]:
# Subtracte 2 vectors

(a - b)

array([[ 9, 13]])

In [7]:
# Scaler

c = 2
u = np.array([[30, 15]])

(c * u).T

array([[60],
       [30]])

In [9]:
# Dot product of 2 vectors
# For 2D vectors, it is equivalent to matrix multiplication

u = np.array([10, 20])
v = np.array([25, 6])

print(10 * 25 + 20 * 6)
np.dot(u,v)

370


370

In [15]:
# Matrix Addition & Subtraction

a = np.array([[12, 10], [4,6], [40, 31],])
b = np.array([[2, 8], [46,63], [50, 10],])

print(a, end=" = a\n\n")
print(b, end=" = b\n\n")

print(a + b)
print(a - b)

[[12 10]
 [ 4  6]
 [40 31]] = a

[[ 2  8]
 [46 63]
 [50 10]] = b

[[14 18]
 [50 69]
 [90 41]]
[[ 10   2]
 [-42 -57]
 [-10  21]]


In [16]:
# Matrix scalar multiplaction

a = 4
b = np.array([[2,5], [3, 7], [8,6],])

a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [19]:
# Matrix and vector multiplication

a = [[5, 10], [15, 20]]
b = [10, 12]

print([[10*5+12*10, 10*15+12*20]])
np.dot(a, b)

[[170, 390]]


array([170, 390])

In [20]:
# Matrix to matrix multiplication

a = [[5, 10], [15, 20], [25, 30],]
b = [[3, 6], [9., 5]]

np.dot(a, b)

array([[105.,  80.],
       [225., 190.],
       [345., 300.]])

In [22]:
# Transpoes a matrix

a = np.array([[5, 10], [15, 20], [25, 30],])

print(a, end=" = a\n\n")
print(a.T, end=" = aT\n\n")

[[ 5 10]
 [15 20]
 [25 30]] = a

[[ 5 15 25]
 [10 20 30]] = aT



In [24]:
# Create an Indetity matrix

I1 = np.eye(2)
I2 = np.eye(3)

print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



In [31]:
# Inverse a matrix
# return the matrix a_inv satifying
# dot(a, a_inv) = dot(a_inv, a) = eye(a.shape[0])

a = np.array([
    [2, 1, 0],
    [0, 1, 0],
    [1, 2, 1]
])

print(a, end=" = a\n\n")
a_inv = np.linalg.inv(a)
print(a_inv, end=" = a_inv\n\n")

np.dot(a, a_inv)

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = a_inv



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])